repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c # frozen: v4.6.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ffb6a759a979008c0e6dff86e39f4745a2d9eac4 # frozen: v3.1.0
    hooks:
      - id: prettier
        files: \.(css|md|yml|yaml)
        args: [--prose-wrap=preserve]

  - repo: https://github.com/psf/black
    rev: 3702ba224ecffbcec30af640c149f231d90aebdb # frozen: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/asottile/blacken-docs
    rev: 960ead214cd1184149d366c6d27ca6c369ce46b6 # frozen: 1.16.0
    hooks:
      - id: blacken-docs

  - repo: https://github.com/asottile/pyupgrade
    rev: 32151ac97cbfd7f9dcd22e49516fb32266db45b4 # frozen: v3.16.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

ci:
  autofix_prs: false
  autofix_commit_msg: "[pre-commit.ci 🤖] Apply code format tools to PR"
  autoupdate_schedule: quarterly
